name: Build the package

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'package.json'
    tags-ignore:
      - 'v*.*.*'

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --no-progress

  static-checks:
    name: Statis checks
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --no-progress

      - name: Checks
        run: yarn static-checks

  tests:
    name: Unit tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --no-progress

      - name: Run unit tests
        run: yarn test

  lines-control:
    name: Lines control
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Load current commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --no-progress

      - name: Build the project
        run: yarn build

      - name: Run example
        run: yarn example
